### ISSUE TITLE
Demo Script Cannot Find "Spirit Core Configuration File for Vendor:Actel Library: SgCore Name:PF_TX_PLL"

### ISSUE THREAD

**Issue by ghalfacree** [Microchip-Vectorblox/VectorBlox-SoC-Video-Kit-Demo#2]
If you bypass the version mismatch reported in #1, you still can't build the project: Libero SoC makes a decent attempt, but the process fails immediately after building the HDMI_TX_C0 component with an error.

### Replication
Edit the TCL script to change the check for Libero SoC V2023.1 to V2023.2 so it will actually run on the current Libero SoC release. Load Libero SoC V2023.2, Ctrl-U to open the script dialogue, find and run the script.

### Expected Results
The demo builds and can be flashed onto the Microchip PolarFire SoC Video Kit.

### Actual Results

![Screenshot from 2023-10-11 14-41-47](https://github.com/Microchip-Vectorblox/VectorBlox-SoC-Video-Kit-Demo/assets/1130041/6668f05d-3378-4054-ba72-5f38ef814e47)

**Comment by cirqueit** [comment]
Libero 2023.2 requires several IP cores versions to be updated in this design. We will upgrade the project for 2023.2 in our next release (w/ required IP core upgrades).

Please use Libero 2023.1 for this release (multiple Libero versions can be installed side-by-side)
https://www.microchip.com/en-us/products/fpgas-and-plds/fpga-and-soc-design-tools/fpga/libero-software-later-versions

**Comment by ghalfacree** [comment]
This is, as above, resolved if you run the current version of the demo script in Libero SoC 2023.1 - but only if you also clear your vault after attempting it in 2023.2.
